# 1. Setup Paths and Data Sources 

Define imports, workspace paths, and the source locations.

In [1]:
from pathlib import Path

import polars as pl

ROOT = Path.cwd().resolve()
DATA_DIR = ROOT / "data"
DATA_DIR.mkdir(exist_ok=True)

DAIOE_SOURCE: str = (
    "https://raw.githubusercontent.com/joseph-data/07_translate_ssyk/main/"
    "03_translated_files/daioe_ssyk2012_translated.csv"
)
SCB_SOURCE: str = (
    "https://raw.githubusercontent.com/joseph-data/AI_Econ_daioe_years_regions/daioe_pull/"
    "data/processed/ssyk12_aggregated_ssyk4_to_ssyk1.parquet"
)

# 2. Load DAIOE and SCB Lazily

Read source files as `LazyFrame` objects for efficient transformations

In [2]:
daioe_lazy_lf = pl.scan_csv(
    DAIOE_SOURCE,
)

scb_lazy_lf = pl.scan_parquet(
    SCB_SOURCE,
)

# 3. Quick Sanity Checks

Preview data

In [3]:
print(daioe_lazy_lf.head(5).collect())

shape: (5, 27)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ ssyk2012_4 ┆ year ┆ daioe_alla ┆ daioe_stra ┆ … ┆ pctl_rank_ ┆ ssyk2012_ ┆ ssyk2012_ ┆ ssyk2012_ │
│ ---        ┆ ---  ┆ pps        ┆ tgames     ┆   ┆ genai      ┆ 1         ┆ 2         ┆ 3         │
│ str        ┆ i64  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│            ┆      ┆ f64        ┆ f64        ┆   ┆ f64        ┆ str       ┆ str       ┆ str       │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0110 Commi ┆ 2010 ┆ null       ┆ null       ┆ … ┆ null       ┆ 0 Armed   ┆ 01        ┆ 011 Commi │
│ ssioned    ┆      ┆            ┆            ┆   ┆            ┆ forces    ┆ Officers  ┆ ssioned   │
│ armed      ┆      ┆            ┆            ┆   ┆            ┆ occupatio ┆           ┆ armed     │
│ forces…    ┆      ┆            ┆            ┆   ┆            ┆ ns        ┆           ┆ forces …  │
│ 0110 Commi ┆ 2011 ┆ null       ┆ null       ┆ … ┆ null       ┆ 0 Armed   ┆ 01        ┆ 011 Commi │
│ ssioned    ┆      ┆            ┆            ┆   ┆            ┆ forces    ┆ Officers  ┆ ssioned   │
│ armed      ┆      ┆            ┆            ┆   ┆            ┆ occupatio ┆           ┆ armed     │
│ forces…    ┆      ┆            ┆            ┆   ┆            ┆ ns        ┆           ┆ forces …  │
│ 0110 Commi ┆ 2012 ┆ null       ┆ null       ┆ … ┆ null       ┆ 0 Armed   ┆ 01        ┆ 011 Commi │
│ ssioned    ┆      ┆            ┆            ┆   ┆            ┆ forces    ┆ Officers  ┆ ssioned   │
│ armed      ┆      ┆            ┆            ┆   ┆            ┆ occupatio ┆           ┆ armed     │
│ forces…    ┆      ┆            ┆            ┆   ┆            ┆ ns        ┆           ┆ forces …  │
│ 0110 Commi ┆ 2013 ┆ null       ┆ null       ┆ … ┆ null       ┆ 0 Armed   ┆ 01        ┆ 011 Commi │
│ ssioned    ┆      ┆            ┆            ┆   ┆            ┆ forces    ┆ Officers  ┆ ssioned   │
│ armed      ┆      ┆            ┆            ┆   ┆            ┆ occupatio ┆           ┆ armed     │
│ forces…    ┆      ┆            ┆            ┆   ┆            ┆ ns        ┆           ┆ forces …  │
│ 0110 Commi ┆ 2014 ┆ null       ┆ null       ┆ … ┆ null       ┆ 0 Armed   ┆ 01        ┆ 011 Commi │
│ ssioned    ┆      ┆            ┆            ┆   ┆            ┆ forces    ┆ Officers  ┆ ssioned   │
│ armed      ┆      ┆            ┆            ┆   ┆            ┆ occupatio ┆           ┆ armed     │
│ forces…    ┆      ┆            ┆            ┆   ┆            ┆ ns        ┆           ┆ forces …  │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [4]:
print(scb_lazy_lf.head(5).collect())

shape: (5, 8)
┌───────┬───────────┬────────────────────┬─────────────┬────────────────────┬───────┬──────┬───────┐
│ level ┆ ssyk_code ┆ occupation         ┆ county_code ┆ county             ┆ sex   ┆ year ┆ value │
│ ---   ┆ ---       ┆ ---                ┆ ---         ┆ ---                ┆ ---   ┆ ---  ┆ ---   │
│ str   ┆ str       ┆ str                ┆ str         ┆ str                ┆ str   ┆ i64  ┆ i64   │
╞═══════╪═══════════╪════════════════════╪═════════════╪════════════════════╪═══════╪══════╪═══════╡
│ SSYK4 ┆ 2343      ┆ Preschool teachers ┆ 24          ┆ Västerbotten       ┆ men   ┆ 2024 ┆ 114   │
│       ┆           ┆                    ┆             ┆ county             ┆       ┆      ┆       │
│ SSYK4 ┆ 4113      ┆ Back office-staff  ┆ 17          ┆ Värmland county    ┆ women ┆ 2017 ┆ 6     │
│ SSYK4 ┆ 5311      ┆ Child care workers ┆ 18          ┆ Örebro county      ┆ women ┆ 2021 ┆ 2377  │
│ SSYK4 ┆ 4212      ┆ Debt-collectors,   ┆ 05          ┆ Östergötland       ┆ women ┆ 2022 ┆ 4     │
│       ┆           ┆ pawnbrokers a…     ┆             ┆ county             ┆       ┆      ┆       │
│ SSYK4 ┆ 8159      ┆ Machine operators  ┆ 01          ┆ Stockholm county   ┆ men   ┆ 2020 ┆ 103   │
│       ┆           ┆ not elsewher…      ┆             ┆                    ┆       ┆      ┆       │
└───────┴───────────┴────────────────────┴─────────────┴────────────────────┴───────┴──────┴───────┘

# 4. Compute the 1-Yr, 3-Yr and 5-Yr Change

Aggregate to employment totals by `level`, `ssyk_code`, `occupation`, `county_code`, `sex`, and `year`, then compute absolute and percent changes over 1, 3, and 5 years using window shifts.

In [5]:
change_keys = [col for col in scb_lazy_lf.collect_schema().names() if col != "value"]
time_col = "year"
group_keys = [col for col in change_keys if col != time_col]

scb_lazy_lf_changes = (
    scb_lazy_lf
    .group_by(change_keys)
    .agg(pl.col("value").sum().alias("emp_count"))
    # Pre-compute shifted values once each
    .with_columns([
        pl.col("emp_count").shift(1).over(group_keys, order_by=time_col).alias("_emp_1y"),
        pl.col("emp_count").shift(3).over(group_keys, order_by=time_col).alias("_emp_3y"),
        pl.col("emp_count").shift(5).over(group_keys, order_by=time_col).alias("_emp_5y"),
    ])
    # Reuse pre-computed shifts
    .with_columns([
        (pl.col("emp_count") - pl.col("_emp_1y")).alias("chg_1y"),
        (pl.col("emp_count") - pl.col("_emp_3y")).alias("chg_3y"),
        (pl.col("emp_count") - pl.col("_emp_5y")).alias("chg_5y"),
        ((pl.col("emp_count") / pl.col("_emp_1y") - 1) * 100).alias("pct_chg_1y"),
        ((pl.col("emp_count") / pl.col("_emp_3y") - 1) * 100).alias("pct_chg_3y"),
        ((pl.col("emp_count") / pl.col("_emp_5y") - 1) * 100).alias("pct_chg_5y"),
    ])
    .drop("_emp_1y", "_emp_3y", "_emp_5y")
)

scb_lazy_lf_changes.collect_schema()

Schema([('level', String),
        ('ssyk_code', String),
        ('occupation', String),
        ('county_code', String),
        ('county', String),
        ('sex', String),
        ('year', Int64),
        ('emp_count', Int64),
        ('chg_1y', Int64),
        ('chg_3y', Int64),
        ('chg_5y', Int64),
        ('pct_chg_1y', Float64),
        ('pct_chg_3y', Float64),
        ('pct_chg_5y', Float64)])

# 5. Derive SSYK2012 Levels in the DAIOE dataset

Split DAIOE SSYK4 into SSYK1-4 and keep SSYK2012 years.

In [6]:
SSYK12_START_YEAR = 2014  # First year of SSYK2012 publication

daioe_lazy_lf_ssyk12 = (
    daioe_lazy_lf
    .with_columns(
        pl.col("ssyk2012_4").str.slice(0, i).alias(f"code_{i}")
        for i in range(1, 5)
    )
    .drop(pl.col("^ssyk2012.*$"))
    .filter(pl.col("year") >= SSYK12_START_YEAR)
)
daioe_lazy_lf_ssyk12.limit(10).collect()

shape: (10, 27)
┌──────┬───────────────┬─────────────────┬─────────────────┬───┬────────┬────────┬────────┬────────┐
│ year ┆ daioe_allapps ┆ daioe_stratgame ┆ daioe_videogame ┆ … ┆ code_1 ┆ code_2 ┆ code_3 ┆ code_4 │
│ ---  ┆ ---           ┆ s               ┆ s               ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ i64  ┆ f64           ┆ ---             ┆ ---             ┆   ┆ str    ┆ str    ┆ str    ┆ str    │
│      ┆               ┆ f64             ┆ f64             ┆   ┆        ┆        ┆        ┆        │
╞══════╪═══════════════╪═════════════════╪═════════════════╪═══╪════════╪════════╪════════╪════════╡
│ 2014 ┆ null          ┆ null            ┆ null            ┆ … ┆ 0      ┆ 01     ┆ 011    ┆ 0110   │
│ 2015 ┆ null          ┆ null            ┆ null            ┆ … ┆ 0      ┆ 01     ┆ 011    ┆ 0110   │
│ 2016 ┆ null          ┆ null            ┆ null            ┆ … ┆ 0      ┆ 01     ┆ 011    ┆ 0110   │
│ 2017 ┆ null          ┆ null            ┆ null            ┆ … ┆ 0      ┆ 01     ┆ 011    ┆ 0110   │
│ 2018 ┆ null          ┆ null            ┆ null            ┆ … ┆ 0      ┆ 01     ┆ 011    ┆ 0110   │
│ 2019 ┆ null          ┆ null            ┆ null            ┆ … ┆ 0      ┆ 01     ┆ 011    ┆ 0110   │
│ 2020 ┆ null          ┆ null            ┆ null            ┆ … ┆ 0      ┆ 01     ┆ 011    ┆ 0110   │
│ 2021 ┆ null          ┆ null            ┆ null            ┆ … ┆ 0      ┆ 01     ┆ 011    ┆ 0110   │
│ 2022 ┆ null          ┆ null            ┆ null            ┆ … ┆ 0      ┆ 01     ┆ 011    ┆ 0110   │
│ 2023 ┆ null          ┆ null            ┆ null            ┆ … ┆ 0      ┆ 01     ┆ 011    ┆ 0110   │
└──────┴───────────────┴─────────────────┴─────────────────┴───┴────────┴────────┴────────┴────────┘

# 6. Align DAIOE Years to SCB Coverage

Extend DAIOE series forward when SCB has later years.

In [7]:
## Here I extend the years to Latest according to the pulled SCB data (2024, yearly)

base = daioe_lazy_lf_ssyk12

# Extend years to latest available in SCB data (2024, yearly)
DAIOE_MAX_YEAR = base.select(pl.max("year")).collect().item()
SCB_MAX_YEAR = scb_lazy_lf.select(pl.max("year")).collect().item()
missing_years = list(range(DAIOE_MAX_YEAR + 1, SCB_MAX_YEAR + 1))

daioe_lazy_lf_extended = (
    base
    if not missing_years
    else pl.concat(
        [
            base,
            base
            .filter(pl.col("year") == DAIOE_MAX_YEAR)
            .drop("year")
            .join(pl.LazyFrame({"year": missing_years}), how="cross")
            .select(base.collect_schema().names()),
        ],
        how="vertical",
    )
)

In [8]:
daioe_lazy_lf_extended.filter(pl.col("year") == SCB_MAX_YEAR).limit(10).collect()

shape: (10, 27)
┌──────┬───────────────┬─────────────────┬─────────────────┬───┬────────┬────────┬────────┬────────┐
│ year ┆ daioe_allapps ┆ daioe_stratgame ┆ daioe_videogame ┆ … ┆ code_1 ┆ code_2 ┆ code_3 ┆ code_4 │
│ ---  ┆ ---           ┆ s               ┆ s               ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ i64  ┆ f64           ┆ ---             ┆ ---             ┆   ┆ str    ┆ str    ┆ str    ┆ str    │
│      ┆               ┆ f64             ┆ f64             ┆   ┆        ┆        ┆        ┆        │
╞══════╪═══════════════╪═════════════════╪═════════════════╪═══╪════════╪════════╪════════╪════════╡
│ 2024 ┆ null          ┆ null            ┆ null            ┆ … ┆ 0      ┆ 01     ┆ 011    ┆ 0110   │
│ 2024 ┆ null          ┆ null            ┆ null            ┆ … ┆ 0      ┆ 02     ┆ 021    ┆ 0210   │
│ 2024 ┆ null          ┆ null            ┆ null            ┆ … ┆ 0      ┆ 03     ┆ 031    ┆ 0310   │
│ 2024 ┆ null          ┆ null            ┆ null            ┆ … ┆ 1      ┆ 11     ┆ 111    ┆ 1111   │
│ 2024 ┆ 31.355038     ┆ 0.25465         ┆ 3.619455        ┆ … ┆ 1      ┆ 11     ┆ 111    ┆ 1112   │
│ 2024 ┆ 33.85648      ┆ 0.269727        ┆ 3.7854          ┆ … ┆ 1      ┆ 11     ┆ 111    ┆ 1113   │
│ 2024 ┆ 32.331161     ┆ 0.260123        ┆ 3.675521        ┆ … ┆ 1      ┆ 11     ┆ 112    ┆ 1120   │
│ 2024 ┆ 38.505562     ┆ 0.333748        ┆ 4.106049        ┆ … ┆ 1      ┆ 12     ┆ 121    ┆ 1211   │
│ 2024 ┆ 38.505562     ┆ 0.333748        ┆ 4.106049        ┆ … ┆ 1      ┆ 12     ┆ 121    ┆ 1212   │
│ 2024 ┆ 34.89122      ┆ 0.270463        ┆ 3.514242        ┆ … ┆ 1      ┆ 12     ┆ 122    ┆ 1221   │
└──────┴───────────────┴─────────────────┴─────────────────┴───┴────────┴────────┴────────┴────────┘

# 7. Build SCB SSYK4 Employment Counts

Aggregate the SCB counts by year and the 4-digit SSYK Level.

In [9]:
print(scb_lazy_lf.head(5).collect())

shape: (5, 8)
┌───────┬───────────┬────────────────────┬─────────────┬────────────────────┬───────┬──────┬───────┐
│ level ┆ ssyk_code ┆ occupation         ┆ county_code ┆ county             ┆ sex   ┆ year ┆ value │
│ ---   ┆ ---       ┆ ---                ┆ ---         ┆ ---                ┆ ---   ┆ ---  ┆ ---   │
│ str   ┆ str       ┆ str                ┆ str         ┆ str                ┆ str   ┆ i64  ┆ i64   │
╞═══════╪═══════════╪════════════════════╪═════════════╪════════════════════╪═══════╪══════╪═══════╡
│ SSYK4 ┆ 2343      ┆ Preschool teachers ┆ 24          ┆ Västerbotten       ┆ men   ┆ 2024 ┆ 114   │
│       ┆           ┆                    ┆             ┆ county             ┆       ┆      ┆       │
│ SSYK4 ┆ 4113      ┆ Back office-staff  ┆ 17          ┆ Värmland county    ┆ women ┆ 2017 ┆ 6     │
│ SSYK4 ┆ 5311      ┆ Child care workers ┆ 18          ┆ Örebro county      ┆ women ┆ 2021 ┆ 2377  │
│ SSYK4 ┆ 4212      ┆ Debt-collectors,   ┆ 05          ┆ Östergötland       ┆ women ┆ 2022 ┆ 4     │
│       ┆           ┆ pawnbrokers a…     ┆             ┆ county             ┆       ┆      ┆       │
│ SSYK4 ┆ 8159      ┆ Machine operators  ┆ 01          ┆ Stockholm county   ┆ men   ┆ 2020 ┆ 103   │
│       ┆           ┆ not elsewher…      ┆             ┆                    ┆       ┆      ┆       │
└───────┴───────────┴────────────────────┴─────────────┴────────────────────┴───────┴──────┴───────┘

In [10]:
scb_lazy_lf_level4 = (
    scb_lazy_lf
        .filter(pl.col("level") == "SSYK4")
        .group_by(["ssyk_code", "year"])
        .agg(pl.col("value").sum().alias("total_count"))
)

scb_lazy_lf_level4.limit(5).collect()

shape: (5, 3)
┌───────────┬──────┬─────────────┐
│ ssyk_code ┆ year ┆ total_count │
│ ---       ┆ ---  ┆ ---         │
│ str       ┆ i64  ┆ i64         │
╞═══════════╪══════╪═════════════╡
│ 5151      ┆ 2021 ┆ 3015        │
│ 2672      ┆ 2016 ┆ 1186        │
│ 7523      ┆ 2014 ┆ 6579        │
│ 3515      ┆ 2021 ┆ 2225        │
│ 3360      ┆ 2023 ┆ 18881       │
└───────────┴──────┴─────────────┘

# 8. Merge DAIOE with SCB SSYK2012 at Level 4 Counts

Join by `year` and the `ssyk_code` the two tables.

This table is used in the aggregation of the daioe metrics.

In [11]:
daioe_scb_years = daioe_lazy_lf_extended\
    .join(
        scb_lazy_lf_level4,
        left_on=["year", "code_4"],
        right_on=["year", "ssyk_code"],
        how="left",
    )

daioe_scb_years.limit(10).collect()

shape: (10, 28)
┌──────┬───────────────┬───────────────┬──────────────┬───┬────────┬────────┬────────┬─────────────┐
│ year ┆ daioe_allapps ┆ daioe_stratga ┆ daioe_videog ┆ … ┆ code_2 ┆ code_3 ┆ code_4 ┆ total_count │
│ ---  ┆ ---           ┆ mes           ┆ ames         ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---         │
│ i64  ┆ f64           ┆ ---           ┆ ---          ┆   ┆ str    ┆ str    ┆ str    ┆ i64         │
│      ┆               ┆ f64           ┆ f64          ┆   ┆        ┆        ┆        ┆             │
╞══════╪═══════════════╪═══════════════╪══════════════╪═══╪════════╪════════╪════════╪═════════════╡
│ 2014 ┆ null          ┆ null          ┆ null         ┆ … ┆ 01     ┆ 011    ┆ 0110   ┆ 861         │
│ 2015 ┆ null          ┆ null          ┆ null         ┆ … ┆ 01     ┆ 011    ┆ 0110   ┆ 1536        │
│ 2016 ┆ null          ┆ null          ┆ null         ┆ … ┆ 01     ┆ 011    ┆ 0110   ┆ 1359        │
│ 2017 ┆ null          ┆ null          ┆ null         ┆ … ┆ 01     ┆ 011    ┆ 0110   ┆ 1183        │
│ 2018 ┆ null          ┆ null          ┆ null         ┆ … ┆ 01     ┆ 011    ┆ 0110   ┆ 1108        │
│ 2019 ┆ null          ┆ null          ┆ null         ┆ … ┆ 01     ┆ 011    ┆ 0110   ┆ 1871        │
│ 2020 ┆ null          ┆ null          ┆ null         ┆ … ┆ 01     ┆ 011    ┆ 0110   ┆ 2286        │
│ 2021 ┆ null          ┆ null          ┆ null         ┆ … ┆ 01     ┆ 011    ┆ 0110   ┆ 2331        │
│ 2022 ┆ null          ┆ null          ┆ null         ┆ … ┆ 01     ┆ 011    ┆ 0110   ┆ 2572        │
│ 2023 ┆ null          ┆ null          ┆ null         ┆ … ┆ 01     ┆ 011    ┆ 0110   ┆ 2851        │
└──────┴───────────────┴───────────────┴──────────────┴───┴────────┴────────┴────────┴─────────────┘

In [12]:
# DAIOE codes with no SCB match
daioe_scb_years_unmatched = daioe_lazy_lf_extended\
    .join(
        scb_lazy_lf_level4,
        left_on=["year", "code_4"],
        right_on=["year", "ssyk_code"],
        how="anti"
    )

daioe_scb_years_unmatched.limit(10).collect()

shape: (0, 27)
┌──────┬───────────────┬─────────────────┬─────────────────┬───┬────────┬────────┬────────┬────────┐
│ year ┆ daioe_allapps ┆ daioe_stratgame ┆ daioe_videogame ┆ … ┆ code_1 ┆ code_2 ┆ code_3 ┆ code_4 │
│ ---  ┆ ---           ┆ s               ┆ s               ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ i64  ┆ f64           ┆ ---             ┆ ---             ┆   ┆ str    ┆ str    ┆ str    ┆ str    │
│      ┆               ┆ f64             ┆ f64             ┆   ┆        ┆        ┆        ┆        │
╞══════╪═══════════════╪═════════════════╪═════════════════╪═══╪════════╪════════╪════════╪════════╡
└──────┴───────────────┴─────────────────┴─────────────────┴───┴────────┴────────┴────────┴────────┘

# 9. Validate the SCB-DAIOE Level 4 Merge

Run quick schema and shape checks on the filtered joined frame before aggregation.

In [13]:
daioe_scb_years.collect_schema()

Schema([('year', Int64),
        ('daioe_allapps', Float64),
        ('daioe_stratgames', Float64),
        ('daioe_videogames', Float64),
        ('daioe_imgrec', Float64),
        ('daioe_imgcompr', Float64),
        ('daioe_imggen', Float64),
        ('daioe_readcompr', Float64),
        ('daioe_lngmod', Float64),
        ('daioe_translat', Float64),
        ('daioe_speechrec', Float64),
        ('daioe_genai', Float64),
        ('pctl_rank_allapps', Float64),
        ('pctl_rank_stratgames', Float64),
        ('pctl_rank_videogames', Float64),
        ('pctl_rank_imgrec', Float64),
        ('pctl_rank_imgcompr', Float64),
        ('pctl_rank_imggen', Float64),
        ('pctl_rank_readcompr', Float64),
        ('pctl_rank_lngmod', Float64),
        ('pctl_rank_translat', Float64),
        ('pctl_rank_speechrec', Float64),
        ('pctl_rank_genai', Float64),
        ('code_1', String),
        ('code_2', String),
        ('code_3', String),
        ('code_4', String),
        ('total_count', Int64)])

# 10. Aggregation of the DAIOEs with the employment data 

Here, I begin the manual steps of aggregating the original daioe's metrics from the level 4 to level 1.

## 10(a). Utility Helper Function

Aggregate SSYK4-1 with a reusable function and add within-year percentiles.

In [14]:
from dataclasses import dataclass


@dataclass
class AggConfig:
    weight_col: str = "total_count"
    prefix: str = "daioe_"
    add_percentiles: bool = True
    pct_scale: int = 100
    descending: bool = False
    # Exposure level boundaries
    pct_l1: int = 20
    pct_l2: int = 40
    pct_l3: int = 60
    pct_l4: int = 80

In [15]:
def aggregate_daioe_level(
    lf: pl.LazyFrame,
    code_col: str,
    level_label: str,
    cfg: AggConfig | None = None,
) -> pl.LazyFrame:
    """
    Aggregate DAIOE metrics by SSYK level with optional weighted averages and percentile ranks.

    Args:
        lf:           Input LazyFrame.
        code_col:     Column name for SSYK code (e.g. "code_1", "code_2").
        level_label:  Label for the aggregation level (e.g. "ssyk1", "ssyk2").
        cfg:          Aggregation configuration (see AggConfig). Defaults to AggConfig().

    """
    if cfg is None:
        cfg = AggConfig()

    daioe_cols = [c for c in lf.collect_schema().names() if c.startswith(cfg.prefix)]
    if not daioe_cols:
        msg = f"No DAIOE columns found with prefix {cfg.prefix!r}"
        raise ValueError(msg)

    w = pl.col(cfg.weight_col)
    mean_exprs = [pl.col(c).mean().alias(f"{c}_avg") for c in daioe_cols]
    weighted_avg_exprs = [
        pl.when(
            (denom := pl.when(pl.col(c).is_not_null()).then(w).otherwise(None).sum()) > 0
        )
        .then((pl.col(c) * w).sum() / denom)
        .otherwise(None)
        .alias(f"{c}_wavg")
        for c in daioe_cols
    ]

    out = (
        lf
        .group_by(["year", code_col])
        .agg(w.sum().alias("weight_sum"), *mean_exprs, *weighted_avg_exprs)
        .with_columns(pl.lit(level_label).alias("level"))
        .rename({code_col: "ssyk_code"})
    )

    if not cfg.add_percentiles:
        return out

    group_keys = ["year", "level"]
    n_expr = pl.len().over(group_keys)
    rank_expr = (
        pl.col(f"^{cfg.prefix}.*_(avg|wavg)$")
        .rank(method="average", descending=cfg.descending)
        .over(group_keys)
    )

    return out.with_columns(
        (
            pl.when(n_expr > 1)
            .then((rank_expr - 1) / (n_expr - 1))
            .otherwise(0.0)
            * cfg.pct_scale
        ).name.prefix("pctl_"),
    )

## 10(b). Aggregating the DAIOEs 

Aggregate SSYK4-1 with a reusable function and add within-year percentiles.

In [16]:
levels_daioe = {
    "code_4": "SSYK4",
    "code_3": "SSYK3",
    "code_2": "SSYK2",
    "code_1": "SSYK1",
}

aggregated = [
    aggregate_daioe_level(daioe_scb_years, col, label)
    for col, label in levels_daioe.items()
]

daioe_all_levels = (
    pl.concat(aggregated)
    .sort(["level", "year", "ssyk_code"])
)

daioe_all_levels.limit(10).collect()

shape: (10, 48)
┌──────┬───────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ year ┆ ssyk_code ┆ weight_sum ┆ daioe_alla ┆ … ┆ pctl_daioe ┆ pctl_daioe ┆ pctl_daio ┆ pctl_daio │
│ ---  ┆ ---       ┆ ---        ┆ pps_avg    ┆   ┆ _lngmod_wa ┆ _translat_ ┆ e_speechr ┆ e_genai_w │
│ i64  ┆ str       ┆ i64        ┆ ---        ┆   ┆ vg         ┆ wavg       ┆ ec_wavg   ┆ avg       │
│      ┆           ┆            ┆ f64        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│      ┆           ┆            ┆            ┆   ┆ f64        ┆ f64        ┆ f64       ┆ f64       │
╞══════╪═══════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 2014 ┆ 0         ┆ 10382      ┆ null       ┆ … ┆ null       ┆ null       ┆ null      ┆ null      │
│ 2014 ┆ 1         ┆ 270311     ┆ 4.831857   ┆ … ┆ 66.666667  ┆ null       ┆ 66.666667 ┆ 66.666667 │
│ 2014 ┆ 2         ┆ 958595     ┆ 5.350139   ┆ … ┆ 77.777778  ┆ null       ┆ 77.777778 ┆ 77.777778 │
│ 2014 ┆ 3         ┆ 547158     ┆ 5.456573   ┆ … ┆ 55.555556  ┆ null       ┆ 55.555556 ┆ 55.555556 │
│ 2014 ┆ 4         ┆ 336357     ┆ 5.672183   ┆ … ┆ 88.888889  ┆ null       ┆ 88.888889 ┆ 88.888889 │
│ 2014 ┆ 5         ┆ 889837     ┆ 4.7938     ┆ … ┆ 44.444444  ┆ null       ┆ 44.444444 ┆ 44.444444 │
│ 2014 ┆ 6         ┆ 31111      ┆ 5.12747    ┆ … ┆ 33.333333  ┆ null       ┆ 33.333333 ┆ 33.333333 │
│ 2014 ┆ 7         ┆ 365544     ┆ 5.497783   ┆ … ┆ 22.222222  ┆ null       ┆ 0.0       ┆ 22.222222 │
│ 2014 ┆ 8         ┆ 297453     ┆ 5.567363   ┆ … ┆ 11.111111  ┆ null       ┆ 22.222222 ┆ 11.111111 │
│ 2014 ┆ 9         ┆ 216657     ┆ 5.086402   ┆ … ┆ 0.0        ┆ null       ┆ 11.111111 ┆ 0.0       │
└──────┴───────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [17]:
print(
    daioe_all_levels
    .group_by("level")
    .len()
    .collect(),
)

shape: (4, 2)
┌───────┬──────┐
│ level ┆ len  │
│ ---   ┆ ---  │
│ str   ┆ u32  │
╞═══════╪══════╡
│ SSYK2 ┆ 506  │
│ SSYK3 ┆ 1628 │
│ SSYK1 ┆ 110  │
│ SSYK4 ┆ 4719 │
└───────┴──────┘

# 11. Build 1-5 Level of EXposure Columns

Create `daioe_<index>_Level_Exposure` columns from weighted percentile ranks (`pctl_daioe_*_wavg`) using quintile-style bins.

In [18]:
# Convert weighted percentile ranks (0..100) into 1-5 exposure levels
pct_cols = [
    c
    for c in daioe_all_levels.collect_schema().names()
    if c.startswith("pctl_daioe_") and c.endswith("_wavg")
]

exposure_exprs = [
    pl.when(pl.col(col).is_null())
    .then(None)
    .when(pl.col(col) <= AggConfig.pct_l1).then(1)
    .when(pl.col(col) <= AggConfig.pct_l2).then(2)
    .when(pl.col(col) <= AggConfig.pct_l3).then(3)
    .when(pl.col(col) <= AggConfig.pct_l4).then(4)
    .otherwise(5)
    .cast(pl.Int8)
    .alias(f"daioe_{col[len('pctl_daioe_'):-len('_wavg')]}_Level_Exposure")
    for col in pct_cols
]

daioe_all_levels = daioe_all_levels.with_columns(exposure_exprs)
print([c for c in daioe_all_levels.collect_schema().names() if c.endswith("_Level_Exposure")])

['daioe_allapps_Level_Exposure', 'daioe_stratgames_Level_Exposure', 'daioe_videogames_Level_Exposure', 'daioe_imgrec_Level_Exposure', 'daioe_imgcompr_Level_Exposure', 'daioe_imggen_Level_Exposure', 'daioe_readcompr_Level_Exposure', 'daioe_lngmod_Level_Exposure', 'daioe_translat_Level_Exposure', 'daioe_speechrec_Level_Exposure', 'daioe_genai_Level_Exposure']

# 12. Merging the data 

After all the data processes are done we now merge `scb_lazy_lf_changes` with the `daioe_all_levels`.

In [19]:
daioe_all_levels.collect_schema()

Schema([('year', Int64),
        ('ssyk_code', String),
        ('weight_sum', Int64),
        ('daioe_allapps_avg', Float64),
        ('daioe_stratgames_avg', Float64),
        ('daioe_videogames_avg', Float64),
        ('daioe_imgrec_avg', Float64),
        ('daioe_imgcompr_avg', Float64),
        ('daioe_imggen_avg', Float64),
        ('daioe_readcompr_avg', Float64),
        ('daioe_lngmod_avg', Float64),
        ('daioe_translat_avg', Float64),
        ('daioe_speechrec_avg', Float64),
        ('daioe_genai_avg', Float64),
        ('daioe_allapps_wavg', Float64),
        ('daioe_stratgames_wavg', Float64),
        ('daioe_videogames_wavg', Float64),
        ('daioe_imgrec_wavg', Float64),
        ('daioe_imgcompr_wavg', Float64),
        ('daioe_imggen_wavg', Float64),
        ('daioe_readcompr_wavg', Float64),
        ('daioe_lngmod_wavg', Float64),
        ('daioe_translat_wavg', Float64),
        ('daioe_speechrec_wavg', Float64),
        ('daioe_genai_wavg', Float64),
        ('level', String),
        ('pctl_daioe_allapps_avg', Float64),
        ('pctl_daioe_stratgames_avg', Float64),
        ('pctl_daioe_videogames_avg', Float64),
        ('pctl_daioe_imgrec_avg', Float64),
        ('pctl_daioe_imgcompr_avg', Float64),
        ('pctl_daioe_imggen_avg', Float64),
        ('pctl_daioe_readcompr_avg', Float64),
        ('pctl_daioe_lngmod_avg', Float64),
        ('pctl_daioe_translat_avg', Float64),
        ('pctl_daioe_speechrec_avg', Float64),
        ('pctl_daioe_genai_avg', Float64),
        ('pctl_daioe_allapps_wavg', Float64),
        ('pctl_daioe_stratgames_wavg', Float64),
        ('pctl_daioe_videogames_wavg', Float64),
        ('pctl_daioe_imgrec_wavg', Float64),
        ('pctl_daioe_imgcompr_wavg', Float64),
        ('pctl_daioe_imggen_wavg', Float64),
        ('pctl_daioe_readcompr_wavg', Float64),
        ('pctl_daioe_lngmod_wavg', Float64),
        ('pctl_daioe_translat_wavg', Float64),
        ('pctl_daioe_speechrec_wavg', Float64),
        ('pctl_daioe_genai_wavg', Float64),
        ('daioe_allapps_Level_Exposure', Int8),
        ('daioe_stratgames_Level_Exposure', Int8),
        ('daioe_videogames_Level_Exposure', Int8),
        ('daioe_imgrec_Level_Exposure', Int8),
        ('daioe_imgcompr_Level_Exposure', Int8),
        ('daioe_imggen_Level_Exposure', Int8),
        ('daioe_readcompr_Level_Exposure', Int8),
        ('daioe_lngmod_Level_Exposure', Int8),
        ('daioe_translat_Level_Exposure', Int8),
        ('daioe_speechrec_Level_Exposure', Int8),
        ('daioe_genai_Level_Exposure', Int8)])

In [20]:
scb_lazy_lf_changes.collect_schema()

Schema([('level', String),
        ('ssyk_code', String),
        ('occupation', String),
        ('county_code', String),
        ('county', String),
        ('sex', String),
        ('year', Int64),
        ('emp_count', Int64),
        ('chg_1y', Int64),
        ('chg_3y', Int64),
        ('chg_5y', Int64),
        ('pct_chg_1y', Float64),
        ('pct_chg_3y', Float64),
        ('pct_chg_5y', Float64)])

In [21]:
final_merge = (
    scb_lazy_lf_changes
    .join(
        daioe_all_levels,
        left_on = ["year", "ssyk_code"],
        right_on = ["year", "ssyk_code"],
        how = "left",
    ).drop(pl.col("level_right"))
)

In [22]:
final_merge.limit(10).collect()

shape: (10, 70)
┌───────┬───────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ level ┆ ssyk_code ┆ occupation ┆ county_cod ┆ … ┆ daioe_lngm ┆ daioe_tra ┆ daioe_spe ┆ daioe_gen │
│ ---   ┆ ---       ┆ ---        ┆ e          ┆   ┆ od_Level_E ┆ nslat_Lev ┆ echrec_Le ┆ ai_Level_ │
│ str   ┆ str       ┆ str        ┆ ---        ┆   ┆ xposure    ┆ el_Exposu ┆ vel_Expos ┆ Exposure  │
│       ┆           ┆            ┆ str        ┆   ┆ ---        ┆ re        ┆ ure       ┆ ---       │
│       ┆           ┆            ┆            ┆   ┆ i8         ┆ ---       ┆ ---       ┆ i8        │
│       ┆           ┆            ┆            ┆   ┆            ┆ i8        ┆ i8        ┆           │
╞═══════╪═══════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ SSYK3 ┆ 123       ┆ Administra ┆ 01         ┆ … ┆ 4          ┆ 4         ┆ 5         ┆ 4         │
│       ┆           ┆ tion and   ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ planning   ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ ma…        ┆            ┆   ┆            ┆           ┆           ┆           │
│ SSYK2 ┆ 51        ┆ Service    ┆ 04         ┆ … ┆ 2          ┆ 2         ┆ 2         ┆ 2         │
│       ┆           ┆ workers    ┆            ┆   ┆            ┆           ┆           ┆           │
│ SSYK4 ┆ 2143      ┆ Engineerin ┆ 09         ┆ … ┆ 5          ┆ 5         ┆ 4         ┆ 5         │
│       ┆           ┆ g professi ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ onals in   ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ e…         ┆            ┆   ┆            ┆           ┆           ┆           │
│ SSYK3 ┆ 154       ┆ Managers   ┆ 05         ┆ … ┆ 4          ┆ 4         ┆ 4         ┆ 4         │
│       ┆           ┆ and        ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ leaders    ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ within re… ┆            ┆   ┆            ┆           ┆           ┆           │
│ SSYK2 ┆ 25        ┆ Occupation ┆ 25         ┆ … ┆ 5          ┆ 5         ┆ 5         ┆ 5         │
│       ┆           ┆ s          ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ requiring  ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ advanced…  ┆            ┆   ┆            ┆           ┆           ┆           │
│ SSYK4 ┆ 2654      ┆ Film,      ┆ 10         ┆ … ┆ 4          ┆ 4         ┆ 4         ┆ 5         │
│       ┆           ┆ stage and  ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ related    ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ direct…    ┆            ┆   ┆            ┆           ┆           ┆           │
│ SSYK4 ┆ 1371      ┆ Production ┆ 04         ┆ … ┆ 3          ┆ 3         ┆ 3         ┆ 3         │
│       ┆           ┆ managers   ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ in         ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ manufac…   ┆            ┆   ┆            ┆           ┆           ┆           │
│ SSYK2 ┆ 76        ┆ Food       ┆ 06         ┆ … ┆ 2          ┆ 2         ┆ 2         ┆ 2         │
│       ┆           ┆ processing ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ and        ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ related    ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ tr…        ┆            ┆   ┆            ┆           ┆           ┆           │
│ SSYK4 ┆ 3214      ┆ Dental and ┆ 18         ┆ … ┆ 2          ┆ 3         ┆ 3         ┆ 3         │
│       ┆           ┆ orthopaedi ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ c technic… ┆            ┆   ┆            ┆           ┆           ┆           │
│ SSYK4 ┆ 2641      ┆ Authors    ┆ 05         ┆ … ┆ 5          ┆ 5         ┆ 5         ┆ 5         │
│       ┆           ┆ and        ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ related    ┆            ┆   ┆            ┆           ┆           ┆           │
│       ┆           ┆ writers    ┆            ┆   ┆            ┆           ┆           ┆           │
└───────┴───────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

# 13. Export the Final Dataset

rite the merged output to parquet for upstream use.

In [45]:
output_path = DATA_DIR / "daioe_scb_years_all_levels.parquet"

final_merge.sink_parquet(output_path)